export const SCHEDULES = {
  sport: {
    novice: [
      {
        date: 0,
        name: "Outdoor Mileage",
        info: '{"goal":"6 moderate pitches","pitches":[]}',
      },
      { date: 0, name: "Skill Acquisition" },
      {
        date: 1,
        name: "Outdoor Mileage",
        info: '{"goal":"4 moderate pitches","pitches":[]}',
      },
      { date: 1, name: "Skill Acquisition" },
      {
        date: 3,
        name: "Aerobic, Respiration, and Capillarity training",
        info: '{"grade":"na","sets":2,"duration":20,"note":""}',
      },
      { date: 3, name: "Skill Acquisition" },
      {
        date: 5,
        name: "Aerobic, Respiration, and Capillarity training",
        info: '{"grade":"na","sets":2,"duration":25,"note":""}',
      },
      { date: 5, name: "Skill Acquisition" },
      {
        date: 7,
        name: "Outdoor Mileage",
        info: '{"goal":"7 moderate pitches","pitches":[]}',
      },
      { date: 7, name: "Skill Acquisition" },
      {
        date: 8,
        name: "Outdoor Mileage",
        info: '{"goal":"5 moderate pitches","pitches":[]}',
      },
      { date: 8, name: "Skill Acquisition" },
      {
        date: 10,
        name: "Aerobic, Respiration, and Capillarity training",
        info: '{"grade":"na","sets":2,"duration":30,"note":""}',
      },
      { date: 10, name: "Skill Acquisition" },
      {
        date: 12,
        name: "Aerobic, Respiration, and Capillarity training",
        info: '{"grade":"na","sets":2,"duration":30,"note":""}',
      },
      { date: 12, name: "Skill Acquisition" },
      {
        date: 14,
        name: "Outdoor Mileage",
        info: '{"goal":"8 moderate pitches","pitches":[]}',
      },
      { date: 14, name: "Skill Acquisition" },
      {
        date: 15,
        name: "Outdoor Mileage",
        info: '{"goal":"6 moderate pitches","pitches":[]}',
      },
      { date: 15, name: "Skill Acquisition" },
      {
        date: 17,
        name: "Aerobic, Respiration, and Capillarity training",
        info: '{"grade":"na","sets":3,"duration":25,"note":""}',
      },
      { date: 17, name: "Skill Acquisition" },
      {
        date: 18,
        name: "Aerobic, Respiration, and Capillarity training",
        info: '{"grade":"na","sets":3,"duration":25,"note":""}',
      },
      { date: 18, name: "Skill Acquisition" },
      {
        date: 19,
        name: "Aerobic, Respiration, and Capillarity training",
        info: '{"grade":"na","sets":2,"duration":25,"note":""}',
      },
      { date: 19, name: "Skill Acquisition" },
      {
        date: 21,
        name: "Outdoor Mileage",
        info: '{"goal":"10 moderate pitches","pitches":[]}',
      },
      { date: 21, name: "Skill Acquisition" },
      {
        date: 22,
        name: "Outdoor Mileage",
        info: '{"goal":"8 moderate pitches","pitches":[]}',
      },
      { date: 22, name: "Skill Acquisition" },
      {
        date: 24,
        name: "Aerobic, Respiration, and Capillarity training",
        info: '{"grade":"na","sets":3,"duration":30,"note":""}',
      },
      { date: 24, name: "Skill Acquisition" },
      {
        date: 25,
        name: "Aerobic, Respiration, and Capillarity training",
        info: '{"grade":"na","sets":3,"duration":30,"note":""}',
      },
      { date: 25, name: "Skill Acquisition" },
      {
        date: 26,
        name: "Aerobic, Respiration, and Capillarity training",
        info: '{"grade":"na","sets":2,"duration":30,"note":""}',
      },
      { date: 26, name: "Skill Acquisition" },
      {
        date: 28,
        name: "Hangboard",
        info: '{"exercise":[{"grip":"jug","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"IMR 2-pad 3F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Medium edge (semi-closed)","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Medium pinch","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"MR 2-pad 2F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Large open-hand edge","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Wide pinch","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Sloper","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"MRP 2-pad 3F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 }]}',
      },
      {
        date: 28,
        name: "Supplementary Exercises",
        info: '{"exercises":[], "note":""}',
      },
      {
        date: 31,
        name: "Hangboard",
        info: '{"exercise":[{"grip":"jug","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"IMR 2-pad 3F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Medium edge (semi-closed)","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Medium pinch","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"MR 2-pad 2F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Large open-hand edge","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Wide pinch","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Sloper","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"MRP 2-pad 3F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 }]}',
      },
      {
        date: 31,
        name: "Supplementary Exercises",
        info: '{"exercises":[], "note":""}',
      },
      {
        date: 34,
        name: "Hangboard",
        info: '{"exercise":[{"grip":"jug","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"IMR 2-pad 3F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Medium edge (semi-closed)","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Medium pinch","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"MR 2-pad 2F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Large open-hand edge","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Wide pinch","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Sloper","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"MRP 2-pad 3F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 }]}',
      },
      {
        date: 34,
        name: "Supplementary Exercises",
        info: '{"exercises":[], "note":""}',
      },
      {
        date: 37,
        name: "Hangboard",
        info: '{"exercise":[{"grip":"jug","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"IMR 2-pad 3F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Medium edge (semi-closed)","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Medium pinch","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"MR 2-pad 2F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Large open-hand edge","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Wide pinch","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Sloper","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"MRP 2-pad 3F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 }]}',
      },
      {
        date: 37,
        name: "Supplementary Exercises",
        info: '{"exercises":[], "note":""}',
      },
      {
        date: 40,
        name: "Hangboard",
        info: '{"exercise":[{"grip":"jug","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"IMR 2-pad 3F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Medium edge (semi-closed)","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Medium pinch","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"MR 2-pad 2F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Large open-hand edge","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Wide pinch","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Sloper","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"MRP 2-pad 3F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 }]}',
      },
      {
        date: 40,
        name: "Supplementary Exercises",
        info: '{"exercises":[], "note":""}',
      },
      {
        date: 43,
        name: "Hangboard",
        info: '{"exercise":[{"grip":"jug","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"IMR 2-pad 3F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Medium edge (semi-closed)","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Medium pinch","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"MR 2-pad 2F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Large open-hand edge","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Wide pinch","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Sloper","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"MRP 2-pad 3F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 }]}',
      },
      {
        date: 43,
        name: "Supplementary Exercises",
        info: '{"exercises":[], "note":""}',
      },
      {
        date: 46,
        name: "Hangboard",
        info: '{"exercise":[{"grip":"jug","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"IMR 2-pad 3F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Medium edge (semi-closed)","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Medium pinch","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"MR 2-pad 2F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Large open-hand edge","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Wide pinch","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"Sloper","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 },{"grip":"MRP 2-pad 3F pocket","set":1,"tut":60,"reps":6,"resistance":0,"exerciseRest":180, "repRest": 5 }]}',
      },
      {
        date: 46,
        name: "Supplementary Exercises",
        info: '{"exercises":[], "note":""}',
      },
      {
        date: 49,
        name: "Warm-up Boulder Ladder",
        info: '{"time":60,"climbs":[]}',
      },
      {
        date: 49,
        name: "Campus",
        info: '{"time":15,"exercise":[{"name":"Matching Ladders","sets":4,"distance":1,"notes":""},{"name":"Basic Ladders","sets":4,"distance":1,"notes":""},{"name":"Max Ladders","sets":4,"distance":2,"notes":""}]}',
      },
      {
        date: 49,
        name: "Supplementary Exercises",
        info: '{"exercises":[], "note":""}',
      },
      {
        date: 52,
        name: "Limit Bouldering",
        info: '{"duration":90,"moves":[]}',
        notes: "",
      },
      {
        date: 52,
        name: "Supplementary Exercises",
        info: '{"exercises":[], "note":""}',
      },
      {
        date: 54,
        name: "Warm-up Boulder Ladder",
        info: '{"time":60,"climbs":[]}',
      },
      {
        date: 54,
        name: "Campus",
        info: '{"time":20,"exercise":[{"name":"Matching Ladders","sets":4,"distance":1,"notes":""},{"name":"Basic Ladders","sets":4,"distance":1,"notes":""},{"name":"Max Ladders","sets":4,"distance":2,"notes":""}]}',
      },
      {
        date: 54,
        name: "Supplementary Exercises",
        info: '{"exercises":[], "note":""}',
      },
      {
        date: 57,
        name: "Limit Bouldering",
        info: '{"duration":90,"moves":[]}',
        notes: "Outdoor",
      },
      {
        date: 59,
        name: "Warm-up Boulder Ladder",
        info: '{"time":60,"climbs":[]}',
      },
      {
        date: 59,
        name: "Campus",
        info: '{"time":25,"exercise":[{"name":"Matching Ladders","sets":4,"distance":1,"notes":""},{"name":"Basic Ladders","sets":4,"distance":1,"notes":""},{"name":"Max Ladders","sets":4,"distance":2,"notes":""}]}',
      },
      {
        date: 59,
        name: "Supplementary Exercises",
        info: '{"exercises":[], "note":""}',
      },
      {
        date: 62,
        name: "Limit Bouldering",
        info: '{"duration":90,"moves":[]}',
        notes: "",
      },
      {
        date: 62,
        name: "Supplementary Exercises",
        info: '{"exercises":[], "note":""}',
      },
      {
        date: 64,
        name: "Warm-up Boulder Ladder",
        info: '{"time":60,"climbs":[]}',
      },
      {
        date: 64,
        name: "Linked Bouldering Circuit",
        info: '{"difficulty":"na","sets":2,"pace":"slow","note":"DC 2:4"}',
      },
      {
        date: 67,
        name: "Warm-up Boulder Ladder",
        info: '{"time":50,"climbs":[]}',
      },
      {
        date: 67,
        name: "Linked Bouldering Circuit",
        info: '{"difficulty":"na","sets":2,"pace":"slow","note":"DC 2:3"}',
      },
      {
        date: 70,
        name: "Redpoint",
        info: '{"climbs":[],"goal":"Bouldery Routes"}',
      },
      {
        date: 71,
        name: "Redpoint",
        info: '{"climbs":[],"goal":"Bouldery Routes"}',
      },
      {
        date: 74,
        name: "Warm-up Boulder Ladder",
        info: '{"time":50,"climbs":[]}',
      },
      {
        date: 74,
        name: "Linked Bouldering Circuit",
        info: '{"difficulty":"na","sets":2,"pace":"slow","note":"DC 2:2"}',
      },
      { date: 77, name: "Redpoint", info: '{"climbs":[],"goal":""}' },
      {
        date: 77,
        name: "Outdoor Mileage",
        info: '{"goal":"2 moderate pitches","pitches":[]}',
      },
      { date: 78, name: "Redpoint", info: '{"climbs":[],"goal":""}' },
      {
        date: 78,
        name: "Outdoor Mileage",
        info: '{"goal":"2 moderate pitches","pitches":[]}',
      },
      {
        date: 81,
        name: "Warm-up Boulder Ladder",
        info: '{"time":40,"climbs":[]}',
      },
      { date: 81, name: "Intervals", info: "DC = 4:4" },
      {
        date: 84,
        name: "Redpoint",
        info: '{"climbs":[],"goal":"Pumpy Routes"}',
      },
      {
        date: 84,
        name: "Outdoor Mileage",
        info: '{"goal":"2 moderate pitches","pitches":[]}',
      },
      {
        date: 85,
        name: "Redpoint",
        info: '{"climbs":[],"goal":"Pumpy Routes"}',
      },
      {
        date: 85,
        name: "Outdoor Mileage",
        info: '{"goal":"2 moderate pitches","pitches":[]}',
      },
      {
        date: 88,
        name: "Warm-up Boulder Ladder",
        info: '{"time":40,"climbs":[]}',
      },
      { date: 88, name: "Intervals", info: "DC = 4:4" },
      {
        date: 91,
        name: "Redpoint",
        info: '{"climbs":[],"goal":"Pumpy Routes"}',
      },
      {
        date: 91,
        name: "Outdoor Mileage",
        info: '{"goal":"2 moderate pitches","pitches":[]}',
      },
      { date: 92, name: "Redpoint", info: '{"climbs":[],"goal":"On sight"}' },
      {
        date: 92,
        name: "Outdoor Mileage",
        info: '{"goal":"2 moderate pitches","pitches":[]}',
      },
      {
        date: 94,
        name: "Redpoint",
        info: '{"climbs":[],"goal":"Pumpy Routes"}',
      },
      {
        date: 94,
        name: "Outdoor Mileage",
        info: '{"goal":"2 moderate pitches","pitches":[]}',
      },
      { date: 95, name: "Redpoint", info: '{"climbs":[],"goal":"On sight"}' },
      {
        date: 95,
        name: "Outdoor Mileage",
        info: '{"goal":"2 moderate pitches","pitches":[]}',
      },
      { date: 97, name: "Redpoint", info: '{"climbs":[],"goal":"On sight"}' },
      {
        date: 97,
        name: "Outdoor Mileage",
        info: '{"goal":"2 moderate pitches","pitches":[]}',
      },
      { date: 99, name: "Redpoint", info: '{"climbs":[],"goal":"On sight"}' },
      {
        date: 99,
        name: "Outdoor Mileage",
        info: '{"goal":"2 moderate pitches","pitches":[]}',
      },
      {
        date: 102,
        name: "Warm-up Boulder Ladder",
        info: '{"time":45,"climbs":[]}',
      },
      {
        date: 105,
        name: "Outdoor Mileage",
        info: '{"goal":"2 moderate pitches","pitches":[]}',
      },
      { date: 105, name: "Redpoint", info: '{"climbs":[],"goal":"On sight"}' },
    ],
  },
};
