export const SCHEDULES = {
  sport: {
    novice: [
      { date: 0, name: "Outdoor Mileage", info: "6 moderate pitches" },
      { date: 0, name: "Skill Acquisition" },
      { date: 1, name: "Outdoor Mileage", info: "4 moderate pitches" },
      { date: 1, name: "Skill Acquisition" },
      {
        date: 3,
        name: "Aerobic, Respiration, and Capillarity training",
        info: "2x20 min",
      },
      { date: 3, name: "Skill Acquisition" },
      {
        date: 5,
        name: "Aerobic, Respiration, and Capillarity training",
        info: "2x25 min",
      },
      { date: 5, name: "Skill Acquisition" },
      { date: 7, name: "Outdoor Mileage", info: "7 moderate pitches" },
      { date: 7, name: "Skill Acquisition" },
      { date: 8, name: "Outdoor Mileage", info: "5 moderate pitches" },
      { date: 8, name: "Skill Acquisition" },
      {
        date: 10,
        name: "Aerobic, Respiration, and Capillarity training",
        info: "2x30 min",
      },
      { date: 10, name: "Skill Acquisition" },
      {
        date: 12,
        name: "Aerobic, Respiration, and Capillarity training",
        info: "2x30 min",
      },
      { date: 12, name: "Skill Acquisition" },
      { date: 14, name: "Outdoor Mileage", info: "8 moderate pitches" },
      { date: 14, name: "Skill Acquisition" },
      { date: 15, name: "Outdoor Mileage", info: "6 moderate pitches" },
      { date: 15, name: "Skill Acquisition" },
      {
        date: 17,
        name: "Aerobic, Respiration, and Capillarity training",
        info: "3x25 min",
      },
      { date: 17, name: "Skill Acquisition" },
      {
        date: 18,
        name: "Aerobic, Respiration, and Capillarity training",
        info: "3x25 min",
      },
      { date: 18, name: "Skill Acquisition" },
      {
        date: 19,
        name: "Aerobic, Respiration, and Capillarity training",
        info: "2x25 min",
      },
      { date: 19, name: "Skill Acquisition" },
      { date: 21, name: "Outdoor Mileage", info: "10 moderate pitches" },
      { date: 21, name: "Skill Acquisition" },
      { date: 22, name: "Outdoor Mileage", info: "8 moderate pitches" },
      { date: 22, name: "Skill Acquisition" },
      {
        date: 24,
        name: "Aerobic, Respiration, and Capillarity training",
        info: "3x30 min",
      },
      { date: 24, name: "Skill Acquisition" },
      {
        date: 25,
        name: "Aerobic, Respiration, and Capillarity training",
        info: "3x30 min",
      },
      { date: 25, name: "Skill Acquisition" },
      {
        date: 26,
        name: "Aerobic, Respiration, and Capillarity training",
        info: "2x30 min",
      },
      { date: 26, name: "Skill Acquisition" },
      { date: 28, name: "Hangboard" },
      { date: 28, name: "Supplementary Exercises" },
      { date: 31, name: "Hangboard" },
      { date: 31, name: "Supplementary Exercises" },
      { date: 34, name: "Hangboard" },
      { date: 34, name: "Supplementary Exercises" },
      { date: 37, name: "Hangboard" },
      { date: 37, name: "Supplementary Exercises" },
      { date: 40, name: "Hangboard" },
      { date: 40, name: "Supplementary Exercises" },
      { date: 43, name: "Hangboard" },
      { date: 43, name: "Supplementary Exercises" },
      { date: 46, name: "Hangboard" },
      { date: 46, name: "Supplementary Exercises" },
      { date: 49, name: "Warm-up Boulder Ladder", info: "60 minutes" },
      { date: 49, name: "Campus", info: "15 minutes" },
      { date: 49, name: "Supplementary Exercises" },
      { date: 52, name: "Limit Bouldering", info: "90 minutes" },
      { date: 52, name: "Supplementary Exercises" },
      { date: 54, name: "Warm-up Boulder Ladder", info: "60 minutes" },
      { date: 54, name: "Campus", info: "20 minutes" },
      { date: 54, name: "Supplementary Exercises" },
      { date: 57, name: "Limit Bouldering", info: "Outdoor" },
      { date: 59, name: "Warm-up Boulder Ladder", info: "60 minutes" },
      { date: 59, name: "Campus", info: "25 minutes" },
      { date: 59, name: "Supplementary Exercises" },
      { date: 62, name: "Limit Bouldering", info: "90 minutes" },
      { date: 62, name: "Supplementary Exercises" },
      { date: 64, name: "Warm-up Boulder Ladder", info: "60 minutes" },
      { date: 64, name: "Linked Bouldering Circuit", info: "DC=2:4" },
      { date: 67, name: "Warm-up Boulder Ladder", info: "50 minutes" },
      { date: 67, name: "Linked Bouldering Circuit", info: "DC=2:3" },
      { date: 70, name: "Redpoint", info: "Bouldery routes" },
      { date: 71, name: "Redpoint", info: "Bouldery routes" },
      { date: 74, name: "Warm-up Boulder Ladder", info: "50 minutes" },
      { date: 74, name: "Linked Bouldering Circuit", info: "DC=2:2" },
      { date: 77, name: "Redpoint" },
      { date: 77, name: "Outdoor Mileage", info: "2 moderate pitches" },
      { date: 78, name: "Redpoint" },
      { date: 78, name: "Outdoor Mileage", info: "2 moderate pitches" },
      { date: 81, name: "Warm-up Boulder Ladder", info: "40 minutes" },
      { date: 81, name: "Intervals", info: "DC = 4:4" },
      { date: 84, name: "Redpoint", info: "Pumpy routes" },
      { date: 84, name: "Outdoor Mileage", info: "2 moderate pitches" },
      { date: 85, name: "Redpoint", info: "Pumpy routes" },
      { date: 85, name: "Outdoor Mileage", info: "2 moderate pitches" },
      { date: 88, name: "Warm-up Boulder Ladder", info: "40 minutes" },
      { date: 88, name: "Intervals", info: "DC = 4:4" },
      { date: 91, name: "Redpoint", info: "Pumpy routes" },
      { date: 91, name: "Outdoor Mileage", info: "2 moderate pitches" },
      { date: 92, name: "Redpoint", info: "On Sight" },
      { date: 92, name: "Outdoor Mileage", info: "2 moderate pitches" },
      { date: 94, name: "Redpoint", info: "Pumpy routes" },
      { date: 94, name: "Outdoor Mileage", info: "2 moderate pitches" },
      { date: 95, name: "Redpoint", info: "On Sight" },
      { date: 95, name: "Outdoor Mileage", info: "2 moderate pitches" },
      { date: 97, name: "Redpoint", info: "On Sight" },
      { date: 97, name: "Outdoor Mileage", info: "2 moderate pitches" },
      { date: 99, name: "Redpoint", info: "On Sight" },
      { date: 99, name: "Outdoor Mileage", info: "2 moderate pitches" },
      { date: 102, name: "Warm-up Boulder Ladder", info: "45 minutes" },
      { date: 105, name: "Outdoor Mileage", info: "2 moderate pitches" },
      { date: 105, name: "Redpoint", info: "On Sight" },
    ],
  },
};
